language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
install:
  - pip install -U pip tox virtualenv codecov
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      pip install -U flake8 ;
      flake8 *.py src --count --select=E901,E999,F821,F822,F823 --statistics ;
    fi
script:
  - tox -e coverage
after_success:
  - codecov
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.3
      dist: trusty
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      # we don't actually need sudo, but that kicks us onto GCE, which means
      # "group: edge" will let us get Ubuntu 14.04 LTS (xenial)
      #group: edge
      sudo: true
    - python: nightly
      dist: trusty
      sudo: false
  allow_failures:
    - python: "3.3"
    - python: "nightly"
